In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr.dtype

dtype('int32')

In [6]:
arr.itemsize

4

In [7]:
arr.shape

(8,)

In [8]:
arr.ndim

1

In [9]:
arr.nbytes

32

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

print(a+b)
print(a*b)
print(a**b)

[11 22 33 44 55]
[ 10  40  90 160 250]
[       10       400     27000   2560000 312500000]


In [16]:
import time
import numpy as np
arraysize = 1000000
def python_version():
    t1 = time.time()
    x=range(arraysize)
    y=range(arraysize)
    z=[x[i] + y[i] for i in range(len(x))]
    return time.time()-t1

def numpy_version():
    t1 = time.time()
    x=np.arange(arraysize)
    y=np.arange(arraysize)
    z=x+y
    return time.time()-t1
t1=python_version()
t2=numpy_version()

print('numpy in this example is : ' + str(t1/t2) + 'faster')


numpy in this example is : 95.14558852818163faster


In [17]:
distancearr = np.array([10,20,30,40,50])
timearr = np.array([12,5,14,6,8])
speedarr = distancearr/timearr
speedarr

array([0.83333333, 4.        , 2.14285714, 6.66666667, 6.25      ])

In [18]:
distancelist = [10,20,30,40,50]
timelist = [12,5,14,6,8]
speedlist = distancelist/timelist
speedlist

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [19]:
a = np.array([10,20,30,40,50])
b = np.array([[1,2,3,4,5],
              [10,20,30,40,50]])
print(b)


[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [20]:
b.shape

(2, 5)

In [21]:
b.dtype

dtype('int32')

In [22]:
b.ndim

2

In [23]:
b[1][3]

40

In [25]:
b[-1][-2]

40

In [35]:
c = np.array([[[1,2,3,4,5],
              [10,20,30,40,50],
             [11,22,33,44,55]],
             
            [[1,2,3,4,5],
              [10,20,30,40,50],
             [11,22,33,43,55]],
             
            [[1,2,3,4,5],
              [10,20,30,40,50],
             [11,22,33,44,55]]])
print(c)


[[[ 1  2  3  4  5]
  [10 20 30 40 50]
  [11 22 33 44 55]]

 [[ 1  2  3  4  5]
  [10 20 30 40 50]
  [11 22 33 43 55]]

 [[ 1  2  3  4  5]
  [10 20 30 40 50]
  [11 22 33 44 55]]]


In [29]:
c.shape

(3, 3, 5)

In [32]:
c.dtype

dtype('int32')

In [33]:
c.ndim

3

In [34]:
c.size

45

In [39]:
c[1][2][3]

43

In [40]:
c[1,2,3]

43

In [41]:
a[1] = 5.5
print(a)

[10  5 30 40 50]


In [45]:
d=a.astype('float32')
print(d.dtype)
print(d)

float32
[10.  5. 30. 40. 50.]


In [46]:
d[1] = 5.5
print(d)

[10.   5.5 30.  40.  50. ]


In [ ]:
arr = np.array[1.0,2.0,3.0,4.0,5.0,6.6]
